"""empty message

Revision ID: 36266e3353b8
Revises: 86f7b3c78f1f
Create Date: 2022-03-07 15:31:47.808070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36266e3353b8'
down_revision = '86f7b3c78f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'points')
    # ### end Alembic commands ###
