"""empty message

Revision ID: 974f8d911e06
Revises: 5efa1f879ce7
Create Date: 2022-03-08 16:50:52.031960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974f8d911e06'
down_revision = '5efa1f879ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_name_uc', 'players', type_='unique')
    op.create_unique_constraint('player_name', 'players', ['last_name', 'first_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_name', 'players', type_='unique')
    op.create_unique_constraint('player_name_uc', 'players', ['last_name', 'first_name'])
    # ### end Alembic commands ###
